# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: Repository_Pipeline
      type: github
      name: GWS-mbH/DOiT-TestDevOps
      ref: refs/heads/master
